QSYS_SIMDIR="."
QUARTUS_INSTALL_DIR=$QUARTUS_ROOTDIR
USER_DEFINED_ELAB_OPTIONS="+vcs+lic+wait -debug_access+pp npu_tb.sv"
SKIP_SIM=1
TOP_LEVEL_NAME=npu_tb

sh setup.sh QUARTUS_INSTALL_DIR=$QUARTUS_INSTALL_DIR USER_DEFINED_ELAB_OPTIONS="\"$USER_DEFINED_ELAB_OPTIONS\"" SKIP_SIM=$SKIP_SIM TOP_LEVEL_NAME=$TOP_LEVEL_NAME > rtl_sim_log

#./simv +vcs+lic+wait
